version: "3.8"
services:
  backend:
    image: "node:16"
    depends_on:
      - database
    ports:
      - "3001:3001"
    environment:
      HTTP_SERVER_PORT: 3001
      DB_HOST: "database"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
      REFRESH_TOKEN_PUBLIC_KEY: ${REFRESH_TOKEN_PUBLIC_KEY}
      REFRESH_TOKEN_PRIVATE_KEY: ${REFRESH_TOKEN_PRIVATE_KEY}
    volumes:
      - "./:/mnt"
    working_dir: "/mnt/backend"
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm run dev || echo '`npm run dev` failed'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3002:3002"
    volumes:
      - "./:/mnt"
    working_dir: "/mnt/frontend"
  database:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - vol-postgres:/data
volumes:
  vol-postgres:
